### PR TITLE
Updated docraptor.yaml to include the pipeline API parameter.

### PR DESCRIPTION
**Pull request by jason-o-matic**

### CODE REVIEW

**Comment by jqr** [comment]
We should release 1.0 on all the clients before applying this patch. See [this discussion](https://3.basecamp.com/3093825/buckets/1451866/messages/248256166).

**Comment by jqr** [comment]
We often forget, but we should also bump the [swagger API version](https://github.com/DocRaptor/docraptor-swagger/blob/master/docraptor.yaml#L4) when releasing this.

**Comment by jason-o-matic** [comment]
> We often forget, but we should also bump the swagger API version when releasing this.

This version isn't related at all to our client versions, correct? It's a version for the server API, right?

**Comment by jason-o-matic** [comment]
> We often forget, but we should also bump the swagger API version when releasing this.

I've updated these and I added a note to the readme so it's more obvious in the future.

**Comment by jason-o-matic** [comment]
> We should release 1.0 on all the clients before applying this patch. See this discussion.

I made PRs for review and posted them in BC.

**Comment by jqr** [comment]
Changed the base branch to next so we can stage a few of these changes.

**Pull request merged**
